# Generated by Django 5.2.8 on 2025-11-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Lead's first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Lead's last name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address (must be unique)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number or mobile", max_length=50
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="Current job title or position",
                        max_length=120,
                    ),
                ),
                (
                    "industry_raw",
                    models.CharField(
                        blank=True,
                        help_text="Industry as provided by lead",
                        max_length=100,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Geographic region or location",
                        max_length=100,
                    ),
                ),
                (
                    "interest_area",
                    models.CharField(
                        blank=True,
                        help_text="Area of business interest",
                        max_length=120,
                    ),
                ),
                (
                    "rough_budget_raw",
                    models.CharField(
                        blank=True,
                        help_text="Budget as originally provided",
                        max_length=100,
                    ),
                ),
                (
                    "rough_budget_normalized_euro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget converted to EUR for comparison",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "first_contacted_raw",
                    models.CharField(
                        blank=True,
                        help_text="Original contact date/time as provided",
                        max_length=100,
                    ),
                ),
                (
                    "first_contacted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Parsed first contact timestamp",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Website"),
                            ("event", "Event"),
                            ("referral", "Referral"),
                            ("list", "Purchased/List"),
                        ],
                        default="web",
                        help_text="How the lead was acquired",
                        max_length=20,
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="Whether lead has given marketing consent",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("qualified", "Qualified"),
                            ("disqualified", "Disqualified"),
                            ("converted", "Converted"),
                        ],
                        default="new",
                        help_text="Current lead qualification status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this lead was first created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="leads_lead_email_f663dc_idx"),
                    models.Index(
                        fields=["region"], name="leads_lead_region_bc64d8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="leads_lead_status_e23abe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeadCompanyMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compatibility_score",
                    models.FloatField(
                        help_text="Numerical compatibility score (0.0-1.0)"
                    ),
                ),
                (
                    "matched_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this match was created"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company being matched",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="The lead being matched",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["compatibility_score"],
                        name="leads_leadc_compati_239ca6_idx",
                    )
                ],
                "unique_together": {("lead", "company")},
            },
        ),
    ]
