# Generated by Django 5.2.8 on 2025-11-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company name (must be unique)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Company website URL"),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        help_text="Business sector (e.g., 'finance', 'healthcare')",
                        max_length=100,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Industry sector (e.g., 'SaaS', 'manufacturing')",
                        max_length=100,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Geographic region (e.g., 'EMEA', 'DACH', 'North America')",
                        max_length=100,
                    ),
                ),
                (
                    "typical_project_budget_euro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Typical project budget in euros",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tech_stack",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of technologies used (e.g., ['aws', 'snowflake', 'salesforce'])",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the company"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["industry"], name="companies_c_industr_6efa2c_idx"
                    ),
                    models.Index(
                        fields=["region"], name="companies_c_region_be6b55_idx"
                    ),
                ],
            },
        ),
    ]
